cortex:
  PRNGKey: 0
  seed: 37
  total_steps: 100
  log_interval: 100

environment:
  environment_name: "LunarLander-v2"
  render_mode: "human"

architecture:
  architecture_name: "mlp"
  layers: [32, 16, 8, 4, 2]
