cortex:
  PRNGKey: 0
  seed: 37
  total_steps: 100
  log_interval: 100

environment:
  id: "FrozenLake-v1"
  render_mode: "human"
  map_name: "8x8"
  is_slippery: true

architecture:
  architecture_name: "mlp"
  layers: [32, 16, 8, 4, 2]
  dropout_rate: 0.25
